### PR TITLE
feat: delete account and all data 

### PR DESCRIPTION
**Pull request by Razvy13**
I've created a separated section for the delete button to delimit a "danger zone"
image

And this is the dialog 
Desktop
image

Mobile
image

@Balastrong What do you think?

### CODE REVIEW

**Review by balastrong-test — APPROVED** [review]
Thanks, looks really good!

I changed a bit the action to use the admin supabase client as it's the one with rights to delete users :D

**Comment by Balastrong** [comment]
> Thanks, looks really good!
> 
> I changed a bit the action to use the admin supabase client as it's the one with rights to delete users :D

Oops, that was obviously me with the test account I used to validate that delete was working fine 😅

**Review by Balastrong — APPROVED** [review]

**Comment by Razvy13** [comment]
No problem! Thank you 😄

**Comment by Razvy13** [comment]
Ah I think you referenced the wrong issues. It should be this [one](https://github.com/Balastrong/myntenance/issues/40)

**Comment by Balastrong** [comment]
Yeah :D

**Pull request merged**
